events:
  TicketCreated:
    id: id.TicketID
    title: domain.tickettitle.TicketTitle
    description: TicketDescription
    author: id.UserID
  UserAssignedToTicket:
    ticket: id.TicketID
    by: id.UserID
  TicketClosed:
    ticket: id.TicketID
    by: id.UserID
  TicketCommented:
    ticket: id.TicketID
    message: TicketCommentMessage
    by: id.UserID
  UserUnassignedFromTicket:
    user: id.UserID
    ticket: id.TicketID
    by: id.UserID
  TicketDescriptionChanged:
    ticket: id.TicketID
    newDescription: TicketDescription
    by: id.UserID
  TicketTitleChanged:
    ticket: id.TicketID
    newTitle: domain.tickettitle.TicketTitle
    by: id.UserID

projections:
  Ticket:
    states:
      - New
      - InProgress
      - Closed
      - Stalled
    createOn: TicketCreated
    transitions:
      UserAssignedToTicket:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> InProgress
      TicketClosed:
        - New -> Closed
        - InProgress -> Closed
        - Stalled -> Closed
      TicketCommented:
        - InProgress -> InProgress
        - New -> New
        - Stalled -> Stalled
      UserUnassignedFromTicket:
        - InProgress -> InProgress
        - InProgress -> Stalled
      TicketDescriptionChanged:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> Stalled
      TicketTitleChanged:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> Stalled

services:
  Tickets:
    projections:
      - Ticket
    methods:
      GetTicketByID:
        in: id.TicketID
        out: GetTicketByIDOut
        type: readonly
      CreateTicket:
        in: CreateTicketIn
        out: CreateTicketOut
        emits:
          - TicketCreated
      AssignUserToTicket:
        in: AssignUserToTicket
        emits:
          - UserAssignedToTicket
      CloseTicket:
        in: CloseTicketIn
        emits:
          - TicketClosed
      CreateComment:
        in: CreateCommentIn
        emits:
          - TicketCommented
      UnassigneUserFromTicket:
        in: UnassigneUserFromTicketIn
        emits:
          - UserUnassignedFromTicket
      UpdateTicket:
        in: UpdateTicketIn
        emits:
          - TicketDescriptionChanged
          - TicketTitleChanged