events:
  TicketCreated:
    id: id.Ticket
    title: TicketTitle
    description: TicketDescription
    author: id.User
  TicketClosed:
    ticket: id.Ticket
    by: id.User
  TicketCommented:
    id: id.Comment
    ticket: id.Ticket
    message: TicketCommentMessage
    by: id.User
  UserAssignedToTicket:
    user: id.User
    ticket: id.Ticket
    by: id.User
  UserUnassignedFromTicket:
    user: id.User
    ticket: id.Ticket
    by: id.User
  TicketDescriptionChanged:
    ticket: id.Ticket
    newDescription: TicketDescription
    by: id.User
  TicketTitleChanged:
    ticket: id.Ticket
    newTitle: TicketTitle
    by: id.User
  UserCreated:
    id: id.User
    name: UserName

projections:
  User:
    states:
      - New
    createOn: UserCreated

  Ticket:
    states:
      - New
      - InProgress
      - Closed
      - Stalled
    createOn: TicketCreated
    transitions:
      UserAssignedToTicket:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> InProgress
      TicketClosed:
        - New -> Closed
        - InProgress -> Closed
        - Stalled -> Closed
      TicketCommented:
        - InProgress -> InProgress
        - New -> New
        - Stalled -> Stalled
      UserUnassignedFromTicket:
        - InProgress -> InProgress
        - InProgress -> Stalled
      TicketDescriptionChanged:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> Stalled
      TicketTitleChanged:
        - New -> New
        - InProgress -> InProgress
        - Stalled -> Stalled

services:
  Users:
    projections:
      - User
    methods:
      GetUserByID:
        in: id.User
        out: service.users.io.GetUserByIDOut
      CreateUser:
        in: service.users.io.CreateUserIn
        out: service.users.io.CreateUserOut
        emits:
          - UserCreated

  Tickets:
    projections:
      - Ticket
      - User
    methods:
      GetTicketByID:
        in: id.Ticket
        out: service.tickets.io.GetTicketByIDOut
        type: readonly
      CreateTicket:
        in: service.tickets.io.CreateTicketIn
        out: service.tickets.io.CreateTicketOut
        emits:
          - TicketCreated
      AssignUserToTicket:
        in: service.tickets.io.AssignUserToTicketIn
        emits:
          - UserAssignedToTicket
      CloseTicket:
        in: service.tickets.io.CloseTicketIn
        emits:
          - TicketClosed
      CreateComment:
        in: service.tickets.io.CreateCommentIn
        out: service.tickets.io.CreateCommentOut
        emits:
          - TicketCommented
      UnassignUserFromTicket:
        in: service.tickets.io.UnassignUserFromTicketIn
        emits:
          - UserUnassignedFromTicket
      UpdateTicket:
        in: service.tickets.io.UpdateTicketIn
        emits:
          - TicketDescriptionChanged
          - TicketTitleChanged